output "table_name" {
  value = module.table.table_name
}

output "user_pool_id" {
  value = module.auth.user_pool_id
}

output "api_endpoint" {
  value = module.api.api_endpoint
}

output "dispatch_queue_url" {
  value = module.dispatch_queue.queue_url
}

output "dispatch_queue_dlq_url" {
  value = module.dispatch_queue.dlq_url
}

# `lambda_function_names` and `lambda_published_versions` (rollback design entrega 1 - docs/
# architecture/reviews/rollback-mechanism-design/codex-round2-final-design.md; `cd.yml` reads the
# latter to build the deploy manifest, function_name -> published version + live alias name - not
# sensitive, no PII/secrets) moved to infra/lambda-manifest.generated.tf (E-020/D-232): they used to
# be hand-maintained here and silently fell behind as infra/main.tf grew (61 real Lambda modules
# today, only 33-34 ever made it into these two lists). That file is generated by `npm run
# generate:lambda-manifest` from every `module "*" { source = "./modules/lambda-function" }` block
# across infra/*.tf - never edit it by hand, `npm run check:lambda-manifest` (CI-blocking) enforces
# that it can never drift again.

output "textract_task_handler_function_arn" {
  description = "Live-alias ARN of TextractTaskHandler - item 3's infra/modules/extraction-workflow module needs this once it's finally instantiated (currently still uninstantiated from infra/main.tf, see NEXT_SESSION_PROMPT.md)."
  value       = local.textract_task_handler_function_arn
}

output "pdf_parser_task_handler_function_arn" {
  description = "Live-alias ARN of PdfParserTaskHandler (M7 item 5, D-035) - item 3's infra/modules/extraction-workflow module needs this once it's finally instantiated (currently still uninstantiated from infra/main.tf, see NEXT_SESSION_PROMPT.md)."
  value       = local.pdf_parser_task_handler_function_arn
}

output "bedrock_extraction_task_handler_function_arn" {
  description = "Live-alias ARN of BedrockExtractionTaskHandler (M7 item 6, D-035 §1.9/§1.11) - item 3's infra/modules/extraction-workflow module needs this once it's finally instantiated (currently still uninstantiated from infra/main.tf, see NEXT_SESSION_PROMPT.md)."
  value       = local.bedrock_extraction_task_handler_function_arn
}

output "extraction_validation_task_handler_function_arn" {
  description = "Live-alias ARN of ExtractionValidationTaskHandler (M7 item 7, D-035 §2/§3) - the fourth and last Lambda item 3's infra/modules/extraction-workflow module needs. With this output, ALL FOUR ASL-referenced functions exist for real - item 3 (instantiating the actual aws_sfn_state_machine) is unblocked, see NEXT_SESSION_PROMPT.md."
  value       = local.extraction_validation_task_handler_function_arn
}

output "extraction_state_machine_arn" {
  description = "The real document-extraction Step Functions Standard state machine ARN (M7 item 3). MUST equal local.extraction_state_machine_arn - ExtractionStarterWorker (item 2, already live in dev) has been calling StartExecution against that deterministic name since before this state machine existed for real."
  value       = module.extraction_workflow.state_machine_arn
}

output "extraction_state_machine_name" {
  description = "Plan-time-known name of the state machine (unlike its ARN, a computed attribute only known after apply) - used by terraform test to assert the name matches local.extraction_state_machine_arn's expected name segment without needing command = apply against the real provider."
  value       = module.extraction_workflow.state_machine_name
}

output "tenant_purge_state_machine_name" {
  description = "Plan-time-known name of the W3-07 tenant-purge state machine (D-124). Must match local.tenant_purge_state_machine_arn's name segment - that deterministic ARN is what the memberships handler (CloseOrganizationService) and the sweeper both receive as an env var and call StartExecution against."
  value       = module.tenant_purge_workflow.state_machine_name
}

output "bff_api_endpoint" {
  description = "The BFF's own dedicated HTTP API endpoint (D-053/D-054) - in production this sits behind CloudFront at the same origin as the SPA under the /bff/* path, never called directly by the browser."
  value       = module.bff_api.api_endpoint
}

output "bff_session_table_name" {
  value = module.bff_session_table.table_name
}

output "deploy_manifest_bucket_name" {
  value = module.deploy_manifests.bucket_name
}

output "document_quarantine_bucket_name" {
  value = module.document_buckets.quarantine_bucket_name
}

output "document_clean_bucket_name" {
  value = module.document_buckets.clean_bucket_name
}

output "malware_protection_enabled" {
  value = module.document_malware_protection.enabled
}

output "import_bucket_name" {
  value = module.import_bucket.bucket_name
}

# ADR-0011: cd.yml reads these three to sync the frontend build and invalidate index.html
# after every deploy (etapa 3/4 of NEXT_SESSION_PROMPT.md's plan).
output "spa_bucket_name" {
  value = module.spa_hosting.bucket_name
}

output "spa_distribution_id" {
  value = module.spa_hosting.distribution_id
}

output "spa_distribution_domain_name" {
  description = "The SPA's real origin (no custom domain yet - see the comment on module.spa_hosting in main.tf). This is what var.app_origin should be set to via -var after the first apply."
  value       = module.spa_hosting.distribution_domain_name
}
